# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: Module 4 Exercise 1 CI Pipeline

trigger: none

pool:
  vmImage: windows-latest

jobs:
- job: buildAndTest
  displayName: Build & Test

  steps:
  - task: PowerShell@2
    name: CreateVars
    displayName: Load namespace variables into ENV
    inputs:
      targetType: 'inline'
      script: |
        $sqlcmdPath = (Get-Command sqlcmd).Path.TrimEnd("\\SQLCMD.EXE");
        $databaseName = "sqlitydemodb";
        
        Write-Host "##vso[task.setvariable variable=sqlcmdPath;isOutput=true]$sqlcmdPath"
        Write-Host "##vso[task.setvariable variable=databaseName;isOutput=true]$databaseName"

        Write-Host $env:SPAWNCTL_ACCESS_TOKEN
    env:
      SPAWNCTL_ACCESS_TOKEN: $(SpawnctlAccessToken)


  - task: PowerShell@2
    name: InstallSpawnctl
    displayName: Install spawnctl
    inputs:
      targetType: 'inline'
      script: |
        echo "Downloading and installing spawnctl..."
        New-Item -Path "$(Pipeline.Workspace)/spawnExeTmp" -ItemType directory -Force;    
        Invoke-WebRequest -Uri "https://run.spawn.cc/spawnctl.exe" -UseBasicParsing -OutFile "$(Pipeline.Workspace)/spawnExeTmp/spawnctl.exe"
        & "$(Pipeline.Workspace)/spawnExeTmp/spawnctl.exe" version

  - task: PowerShell@2
    name: createContainer
    displayName: Create SQL Server Instance on Spawn Data-Container
    inputs:
      targetType: 'inline'
      script: |
        $dataImageName = 'mssql';
        ## $SpawctlAccessToken = $env:SPAWNCTL_ACCESS_TOKEN
        
        $containerName= & "$(Pipeline.Workspace)/spawnExeTmp/spawnctl.exe" create data-container --image $dataImageName --lifetime 30m -q
        $containerJSON= & "$(Pipeline.Workspace)/spawnExeTmp/spawnctl.exe" get data-container $containerName -o json
        $containerInfo = ConvertFrom-JSON -inputObject $containerJSON;
        $containerFQDN=$containerInfo.host+", "+$containerInfo.port;
        $containerUser=$containerInfo.user;
        $containerPassword=$containerInfo.password;
        
        echo "Successfully created Spawn data container '$containerName'"
        
        Write-Host "##vso[task.setvariable variable=containerFQDN;isOutput=true]$containerFQDN"
        Write-Host "##vso[task.setvariable variable=containerUser;isOutput=true]$containerUser"
        Write-Host "##vso[task.setvariable variable=containerPassword;isOutput=true]$containerPassword"
        Write-Host "##vso[task.setvariable variable=containerName;isOutput=true]$containerName"
        ## Write-Host ('::add-mask::$containerPassword');
        ## Write-Host ('::add-mask::$containerName');
    env:
      SPAWNCTL_ACCESS_TOKEN: $(SpawnctlAccessToken)









  - script: echo Hello, world!
    displayName: 'Run a one-line script'
