USE master
GO

IF(DB_ID('$(MODULE1DEMODB)')IS NOT NULL)
BEGIN
	-- EXEC returns the database context to the prior value once complete, despite the USE statement within.
	EXEC('USE $(MODULE1DEMODB);ALTER DATABASE $(MODULE1DEMODB) SET SINGLE_USER WITH ROLLBACK IMMEDIATE;');
	DROP DATABASE $(MODULE1DEMODB);
END
GO
CREATE DATABASE $(MODULE1DEMODB)
GO

USE $(MODULE1DEMODB)
GO